#!/usr/bin/env bash
# Stage everything the air-gapped host needs, on a machine WITH internet.
# Produces ./airgap-bundle/ (images as tarballs + the Ollama model blobs) to
# copy to the offline host. Nothing here contacts the internet at deploy time —
# this is the one and only online step.
#
#   GEN_MODEL=qwen2.5:7b-instruct \
#   CLASSIFY_MODEL=qwen2.5:3b-instruct \
#   SUPABASE_DOCKER_DIR=/path/to/supabase/docker \
#   ./stage-models.sh
#
# See deploy/airgap/README.md for the full flow.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
OUT="${OUT:-$HERE/airgap-bundle}"
GEN_MODEL="${GEN_MODEL:-qwen2.5:7b-instruct}"
CLASSIFY_MODEL="${CLASSIFY_MODEL:-}"          # optional lighter model for classify/rewrite
OLLAMA_IMAGE="${OLLAMA_IMAGE:-ollama/ollama:0.5.4}"
SUPABASE_DOCKER_DIR="${SUPABASE_DOCKER_DIR:-}"

mkdir -p "$OUT"
echo "==> staging into $OUT"

# 1. Build our two images (offline-ready: rag bakes in BGE + reranker; web is a
#    standalone Next server). Public build args are optional today (no browser
#    Supabase client yet) — pass NEXT_PUBLIC_* here if you later add one.
echo "==> building sainik/rag:local"
docker build -t sainik/rag:local "$REPO_ROOT/services/rag"

echo "==> building sainik/web:local"
docker build -t sainik/web:local \
  ${NEXT_PUBLIC_SUPABASE_URL:+--build-arg NEXT_PUBLIC_SUPABASE_URL="$NEXT_PUBLIC_SUPABASE_URL"} \
  ${ANON_KEY:+--build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="$ANON_KEY"} \
  "$REPO_ROOT/apps/web"

# 2. Pull the Ollama runtime and the language model(s) into a throwaway volume,
#    then pack the model blobs. The air-gapped host restores them (README §5).
echo "==> pulling $OLLAMA_IMAGE and models"
docker pull "$OLLAMA_IMAGE"
docker volume create sainik_stage_ollama >/dev/null
docker rm -f sainik_stage_ollama_c >/dev/null 2>&1 || true
docker run -d --name sainik_stage_ollama_c -v sainik_stage_ollama:/root/.ollama "$OLLAMA_IMAGE" >/dev/null
echo "    waiting for ollama to be ready..."
until docker exec sainik_stage_ollama_c ollama list >/dev/null 2>&1; do sleep 1; done
docker exec sainik_stage_ollama_c ollama pull "$GEN_MODEL"
[ -n "$CLASSIFY_MODEL" ] && docker exec sainik_stage_ollama_c ollama pull "$CLASSIFY_MODEL"
docker exec sainik_stage_ollama_c ollama list
docker rm -f sainik_stage_ollama_c >/dev/null
docker run --rm -v sainik_stage_ollama:/root/.ollama -v "$OUT":/out alpine \
  tar czf /out/ollama_models.tgz -C /root/.ollama .
docker volume rm sainik_stage_ollama >/dev/null
echo "    saved ollama_models.tgz"

# 3. Optionally pull + save the upstream Supabase images so the offline host
#    needs no registry access at all.
if [ -n "$SUPABASE_DOCKER_DIR" ]; then
  echo "==> pulling upstream Supabase images"
  ( cd "$SUPABASE_DOCKER_DIR" && docker compose pull )
  mapfile -t SB_IMAGES < <( cd "$SUPABASE_DOCKER_DIR" && docker compose config --images | sort -u )
  echo "    saving ${#SB_IMAGES[@]} supabase images"
  docker save "${SB_IMAGES[@]}" | gzip > "$OUT/supabase-images.tar.gz"
else
  echo "==> SUPABASE_DOCKER_DIR not set — skipping upstream image save."
  echo "    (Stage the Supabase self-hosting images separately if the offline"
  echo "     host has no registry access.)"
fi

# 4. Save our images + the ollama runtime image.
echo "==> saving application images"
docker save sainik/rag:local sainik/web:local "$OLLAMA_IMAGE" | gzip > "$OUT/app-images.tar.gz"

cat > "$OUT/MANIFEST.txt" <<EOF
Sainik Sahayak air-gap bundle
generated by stage-models.sh

app-images.tar.gz     : sainik/rag:local, sainik/web:local, $OLLAMA_IMAGE
ollama_models.tgz     : $GEN_MODEL${CLASSIFY_MODEL:+, $CLASSIFY_MODEL}
supabase-images.tar.gz: $( [ -n "$SUPABASE_DOCKER_DIR" ] && echo "present" || echo "NOT INCLUDED — stage separately" )

Record these exact tags in your .env:
  GENERATION_MODEL=$GEN_MODEL
  OLLAMA_CLASSIFY_MODEL=$CLASSIFY_MODEL
  OLLAMA_IMAGE=$OLLAMA_IMAGE
EOF

echo
echo "==> done. Bundle contents:"
ls -lh "$OUT"
echo
echo "Copy $OUT to the air-gapped host and follow deploy/airgap/README.md §5."
